[project]
name = "toy-django"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.8",
    "django-ninja>=1.5.0",
    "gunicorn>=23.0.0",
    "pytest-django>=4.11.1",
]
